#!/usr/bin/env bash
# wallpaper-theme.sh — make the rice follow the wallpaper.
#   wallpaper-theme.sh <image>   theme Hyprland borders + waybar from <image>
#   wallpaper-theme.sh --current  theme from skwd's current wallpaper
#   wallpaper-theme.sh --watch    theme once, then re-theme on every change
# Started from hyprland.start. Uses matugen (no config needed, JSON output).
set -uo pipefail

SCHEME="$HOME/.config/hypr/scheme/current.lua"
COLORS_CSS="$HOME/.config/waybar/colors.css"

theme_image() {
    local img="$1"
    [[ -f "$img" ]] || { echo "wallpaper-theme: not a file: $img" >&2; return 1; }

    local json
    json=$(matugen image -j hex --dry-run --prefer darkness "$img" 2>/dev/null) || {
        echo "wallpaper-theme: matugen failed for $img" >&2; return 1
    }

    # Render scheme/current.lua + waybar/colors.css from matugen JSON
    MATUGEN_JSON="$json" SCHEME_OUT="$SCHEME" CSS_OUT="$COLORS_CSS" python3 - <<'EOF'
import json, os, re

def camel(s):
    parts = s.split('_')
    return parts[0] + ''.join(p[:1].upper() + p[1:] for p in parts[1:])

d = json.loads(os.environ['MATUGEN_JSON'])
colors = d['colors']
mode = 'dark' if d.get('is_dark_mode', True) else 'light'

def hex_of(token):
    try:
        return colors[token].get(mode, {}).get('color') or colors[token]['default']['color']
    except KeyError:
        return '#000000'

vals = {}
for token in colors:
    if token in ('source_color',):
        continue
    vals[camel(token)] = hex_of(token).lstrip('#')

# terminal palette from base16 (base00..base0F, same dark/light/default shape)
base16 = d.get('base16', {})
for i in range(16):
    key = 'base%02X' % i
    try:
        vals[f'term{i}'] = (base16[key].get(mode, {}).get('color')
                            or base16[key]['default']['color']).lstrip('#')
    except KeyError:
        vals[f'term{i}'] = '000000'

# handy aliases used around the rice
vals.setdefault('text', vals.get('onBackground', 'ffffff'))
vals.setdefault('subtext1', vals.get('onSurfaceVariant', 'ffffff'))
vals.setdefault('subtext0', vals.get('outline', 'ffffff'))
vals.setdefault('base', vals.get('background', '000000'))
vals.setdefault('mantle', vals.get('background', '000000'))
vals.setdefault('crust', vals.get('surfaceDim', '000000'))

with open(os.environ['SCHEME_OUT'], 'w') as f:
    f.write('return {\n')
    for k in sorted(vals):
        f.write(f'  {k} = "{vals[k]}",\n')
    f.write('}\n')

css = (
    f"/* generated by wallpaper-theme.sh — do not edit */\n"
    f"@define-color primary #{vals.get('primary', 'ffffff')};\n"
    f"@define-color on-primary #{vals.get('onPrimary', '000000')};\n"
    f"@define-color surface #{vals.get('surface', '000000')};\n"
    f"@define-color on-surface #{vals.get('onSurface', 'ffffff')};\n"
    f"@define-color outline #{vals.get('outline', '888888')};\n"
)
with open(os.environ['CSS_OUT'], 'w') as f:
    f.write(css)

print(f"PRIMARY={vals.get('primary', 'ffffff')}")
print(f"ONSURFACEVARIANT={vals.get('onSurfaceVariant', 'ffffff')}")
EOF

    # Apply Hyprland border colors live (no reload needed).
    # NOTE: `hyprctl keyword` is rejected on Lua configs ("use eval"),
    # so push the colors through hl.config() via `hyprctl eval`.
    local primary onsv
    primary=$(grep -oP '^\s*primary = "\K[0-9a-fA-F]+' "$SCHEME" | head -n 1)
    onsv=$(grep -oP '^\s*onSurfaceVariant = "\K[0-9a-fA-F]+' "$SCHEME" | head -n 1)
    if [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]] && command -v hyprctl &>/dev/null; then
        hyprctl eval "hl.config({ general = { col = { active_border = \"rgba(${primary}e6)\", inactive_border = \"rgba(${onsv}11)\" } } })" >/dev/null 2>&1 || true
    fi

    # Reload waybar so colors.css takes effect
    pkill -SIGUSR2 -x waybar 2>/dev/null || true

    notify-send 'Theme updated' "$(basename "$img")" -a 'wallpaper-theme' & disown
}

case "${1:-}" in
    --watch)
        # Theme once from the current wallpaper, then follow changes.
        # skwd-helm watch --exec substitutes %path% per wallpaper event.
        cur=$(skwd-helm current --json 2>/dev/null | jq -r '.outputs[0].path // empty')
        [[ -n "$cur" ]] && theme_image "$cur"
        exec skwd-helm watch --exec "$HOME/.config/hypr/scripts/wallpaper-theme.sh %path%"
        ;;
    --current)
        cur=$(skwd-helm current --json 2>/dev/null | jq -r '.outputs[0].path // empty')
        [[ -n "$cur" ]] || { echo "wallpaper-theme: no current wallpaper" >&2; exit 1; }
        theme_image "$cur"
        ;;
    "")
        echo "usage: wallpaper-theme.sh <image> | --current | --watch" >&2
        exit 2
        ;;
    *)
        theme_image "$1"
        ;;
esac
