[global]
    monitor = 0
    follow = mouse
    width = 350
    height = (0, 100)
    origin = top-right
    offset = 15, 15
    scale = 0
    notification_limit = 5
    progress_bar = false

    indicate_hidden = no
    transparency = 0
    separator_height = 0
    padding = 12
    horizontal_padding = 14
    text_icon_padding = 0
    frame_width = 1
    gap_size = 6
    separator_color = frame
    sort = yes
    idle_threshold = 120

    font = JetBrainsMono Nerd Font 10
    line_height = 0
    markup = full
    format = "<b>%s</b>\n%b"
    alignment = left
    vertical_alignment = center
    show_age_threshold = 60
    ellipsize = middle
    ignore_newline = no
    stack_duplicates = true
    hide_duplicate_count = false
    show_indicators = no

    icon_position = left
    min_icon_size = 32
    max_icon_size = 48
    icon_path = /usr/share/icons/hicolor/48x48/status/:/usr/share/icons/hicolor/48x48/devices/
    corner_radius = 12

[urgency_low]
    background = "{{colors.surface.default.hex}}E6"
    foreground = "{{colors.on_surface.default.hex}}"
    frame_color = "{{colors.outline.default.hex}}"
    timeout = 5

[urgency_normal]
    background = "{{colors.surface.default.hex}}E6"
    foreground = "{{colors.on_surface.default.hex}}"
    frame_color = "{{colors.primary.default.hex}}"
    timeout = 5

[urgency_critical]
    background = "{{colors.surface.default.hex}}F2"
    foreground = "{{colors.on_surface.default.hex}}"
    frame_color = "{{colors.error.default.hex}}"
    timeout = 0
